# Generated by Django 3.1.5 on 2021-01-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
