# Generated by Django 3.1.5 on 2021-01-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Текст')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account', verbose_name='Аккаунт')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post', verbose_name='Лайк под постом')),
            ],
            options={
                'verbose_name': 'Лайк под постом',
                'verbose_name_plural': 'Лайки под постами',
                'unique_together': {('post', 'account')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account', verbose_name='Аккаунт')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment', verbose_name='Лайк под комментарием')),
            ],
            options={
                'verbose_name': 'Лайк под комментарием',
                'verbose_name_plural': 'Лайки под комментариями',
                'unique_together': {('comment', 'account')},
            },
        ),
    ]
