# Generated by Django 3.1.5 on 2021-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_commentlike_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Логин'),
        ),
    ]
