# Generated by Django 3.1.5 on 2021-01-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210123_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
