# Generated by Django 3.1.5 on 2021-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210124_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(error_messages={'unique': 'Аккаунт с таким логином уже существует'}, max_length=1000, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'Аккаунт с таким именем пользователя уже существует'}, max_length=1000, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
