# Generated by Django 3.1.5 on 2021-02-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_post_views_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dt_created'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
